[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn app:app --workers=3 --timeout=120 --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
FLASK_ENV = "production"
FLASK_DEBUG = "false"
